version: '3.7'
services:
  rest:
    build: ./api
    environment:
      - CHOKIDAR_USEPOLLING=true
      - MONGO_URI=mongodb://mongo/store
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./api/src:/api/src:cached
    depends_on:
      - mongo
  graphql:
    build: ./graphql-api
    environment:
      - CHOKIDAR_USEPOLLING=true
      - MONGO_URI=mongodb://mongo/store
    restart: always
    ports:
      - '4000:4000'
    volumes:
      - ./graphql-api/src:/graphql-api/src:cached
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
